export * from './Hero';
export * from './Services';
export * from './Team';
export * from './Contact';
export * from './Testimonials';
export * from './Blog';
export * from './CaseStudies';
export * from './IAS';
export * from './DemoSection';